name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - Jose

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_JOSE }}
          REMOTE_HOST: ${{ secrets.DNS_JOSE }}
          REMOTE_USER: ${{ secrets.USERN }}
          TARGET: ${{ secrets.TARGET_DIR }}